spring:
#  profiles:
#    active: local
  datasource:
    platform: h2
    initialization-mode: always
    url: jdbc:h2:tcp://localhost/~/product
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generate-mappings: false
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace